### PR TITLE
Create Get-NetstatObject.ps1

### PR DESCRIPTION
**Pull request by mwilco03**

### CODE REVIEW

**Comment by mwilco03** [comment]
Per conversation ref: https://github.com/davehull/Kansa/issues/207
Submitted pull request

**Comment by davehull** [comment]
Do you know if there's a specific version of PS or the Get-NetTCPConnection cmdlet that returns the OwningProcess property? In my local lab running PS 5.1 and that property does not exist. Also given that Get-NetTCPConnection only returns TCP connections, it's probably worth renaming this collector from Get-NetstatObject.ps1 to something like Get-NetstatTCP.ps1.

**Comment by mwilco03** [comment]
I tested on two verisons the oldest being 5.1.17134.858 
Could you try the following?
Get-WMIObject -namespace Root\StandardCIMV2 -Class MSFT_NetTCPConnection 
Piping that to gm or ogv to see if the wmi object has owningprocess ?
Could rewrite it with WMI if that works instead of Get-NetTCPConnection 

I agree with the renaming.

**Comment by covertpanda** [comment]
Compatible after v3.0+ for PowerShell, utilizing the Get-CimInstance is a newer, better implementation. It is faster than the Get-WmiObject commands, and comply better with CIM and WSMAN standards, allowing better cross-platform compatability and more flexibility. Get-CimInstance (and all *-Cim* cmdlets) are able to leverage the WSMAN protocol, whereas WMI cmdlets can only use DCOM RPC. By making one tweak, it can increase speed, increase compatibility, and is implemented in native PowerShell since v3.0.

`Get-CimInstance -Namespace root/StandardCimv2 -ClassName MSFT_NetTCPConnection`

Should be the newer, more PS way to accomplish the same task.

@mwilco03  thoughts?

**Comment by mwilco03** [comment]
100% agree with this assessment @davehull can you validate from your local lab?

**Comment by davehull** [comment]
I should have some time to check this out tomorrow. Thanks.

**Comment by mwilco03** [comment]
@davehull @covertpanda  
Per the discussion, I have refactored the code to achieve two goals, first be more readable, secondarily I have pulled the UDP information as well.
 
I'm having a rough go at joining the two like I did in the previous script but as far as using CIM Instances go thoughts? 
Was this ever able to be tested in the lab enviroment?

$NetworkObject=@{}
$ProcessObject=@{}

Get-CimInstance -Namespace root/cimv2 -ClassName win32_process|
    Select-Object ProcessName,Path,CommandLine,ExecutablePath,Handle,ProcessId,ParentProcessID,ThreadCount,
        @{Name="User";Expression={($_|Invoke-CimMethod -MethodName GetOwner).User};},
        @{Name="Domain";Expression={($_|Invoke-CimMethod -MethodName GetOwner).Domain};}|
            %{$ProcessObject[[int]$_.Handle]=$_}

Get-CimInstance -Namespace root/StandardCimv2 -ClassName MSFT_NetTCPConnection|
    Select-Object CreationTime,LocalAddress,LocalPort,OwningProcess,RemoteAddress,RemotePort,PSComputerName,
        @{Name="Protocol";Expression={"TCP"};}|
            %{$NetworkObject[[int]$_.OwningProcess]=$_}

Get-CimInstance -Namespace root/StandardCimv2 -ClassName MSFT_NetUDPEndpoint|
    Select-Object CreationTime,LocalAddress,LocalPort,OwningProcess,RemoteAddress,RemotePort,PSComputerName,
        @{Name="Protocol";Expression={"UDP"};}|
            %{$NetworkObject[[int]$_.OwningProcess]=$_}

**Comment by davehull** [comment]
Have you updated the PR? I've got some time today to check it out.

**Comment by mwilco03** [comment]
No sorry, I’ll get it updated today.

**Comment by mwilco03** [comment]
Finally got back to this updated PR

**Comment by mwilco03** [comment]
Going through old requests & wondering if you've had a chance to test this.

**Pull request merged**
